### ISSUE TITLE
Use auth-source to get password automatically

### ISSUE THREAD

**Issue by AkibAzmain** [alphapapa/ement.el#109]
There is a nice library called "auth-source" in Emacs.  It allows get password from various sources like `pass`, `~/.authinfo`, etc.  Ement should use it IMO, instead of getting for password through minibuffer (ERC does prompt, but uses auth-source if if I leave the password empty).

**Comment by alphapapa** [comment]
I am well aware of `auth-source`, unfortunately.  Please see my commentary on it: https://old.reddit.com/r/emacs/comments/8lvda6/is_authsource_from_the_dark_side/  Due to those issues, it does not seem adequate for general use.

**Comment by AkibAzmain** [comment]
Is there any alternative?  Can you consider adding a user option for obtaining the password?  Otherwise I would write a wrapper for `ement-connect` anyway.

**Comment by AkibAzmain** [comment]
However, I must agree that the pass backend (that's what I use) is written poorly, and I needed some advice to fix it.

**Comment by AkibAzmain** [comment]
You have add `wontfix` label, is it because you're just not interest or do you oppose the feature (or burden, depending on what you think about `auth-source`)?

**Comment by alphapapa** [comment]
Rather than writing an additional API to get secrets, which would then need to continue to be supported, I'd generally prefer that you write a wrapper to suit your needs.  Just call `ement-connect` with the arguments you need.

But please note carefully that Matrix is designed so that the user need not continually enter a password; it's entered once on a device, and then a session token is stored.

Note as well that @akater has already done something like that: https://gitlab.com/akater/emacs-ement-extras  Maybe it will suit your needs.

I marked this a wontfix because I do not intend to support `auth-source` unless and until its API is improved and the problems I showed are fixed.  IMO it's not suitable for end-users in its current state, and were this package to support it, users would inevitably complain here and ask for help working around problems in `auth-source`, which I don't intend to offer support for.

**Comment by AkibAzmain** [comment]
Thanks for the clarification.
