### ISSUE TITLE
Mentioning group members when composing messages

### ISSUE THREAD

**Issue by piater** [alphapapa/ement.el#115]
It took me a while to figure out how to mention addressees when composing a message. The README only advises
> Complete members and rooms at point: `C-M-i`

but this won't be found when searching the page for "mention", and it does not mention that members must begin with `@`. This member completion is limited in that it works only in the minibuffer, and only if there is a unique match. Some more usage detail is buried the doc string of `ement-complete-user-id`.

Although its usage is largely intuitive to most users, I suggest documenting the most important aspects explicitly, and activating member completion in compose buffers.

To complement the above functionality and to provide full control, I created the following helper function that may be useful to others:

```
(defun ement-org-store-user (user-id)
  "Store a user for mentioning in an Ement message using `org-insert-link'.
Choose the user with completion; see `ement-complete-user-id' for details."
  (interactive (list (ement-complete-user-id)))
  (push (list
	 (concat "https://matrix.to/#/" (url-hexify-string user-id))
	 (ement--user-displayname-in ement-room (gethash user-id ement-users)))
	org-stored-links))
```

**Comment by alphapapa** [comment]
Hi,

Thanks for bringing this up.  "Mentions" in Matrix are a bit confusing.  Clients are generally responsible for recognizing their local users' names and IDs in messages, regardless of any other formatting.  

But it's also common for clients to "pill" names and IDs in outgoing messages by replacing the username with an HTML link in the HTML-formatted version of the message.  In Ement, names and IDs are recognized in outgoing messages when they are prefixed by `@` or suffixed by `:`, which seems reasonably consistent with how Element does it (unlike Element, we don't build a regexp that matches all members in a room, because some rooms are very large--i.e. it wouldn't seem like a good idea to do that in #matrix:matrix.org, which has over 30,000 members).

So, yes, this should be documented more clearly.

And the lack of the completion command in compose buffers is indeed an oversight.  Thanks.

**Comment by chasecaleb** [comment]
Member completions in compose buffers would be great for me! I use company-mode for completions in buffers, but that isn't an option in the minibuffer... so being able to use the compose buffer when I want completions with company-mode would be great.
