### ISSUE TITLE
Org formatting in replies

### ISSUE THREAD

**Issue by Wibjarm** [alphapapa/ement.el#30]
Formatting with `#'ement-room-send-org-filter` isn't applied properly when composing replies.

**Comment by jeffbowman** [comment]
Spent some time debugging this, it looks like it is going through the org filter, the is the result from the filter: 

```
<p>
&gt; &lt;wolfjb&gt; test message - debugging, please ignore
</p>

<p>
called <code>ement-room-write-reply</code> with <code>ement-room-send-org-filter</code> set</p>
```

however, what I see in the buffer is this:

```
In reply to wolfjb 

test message - debugging, please ignore

called =ement-room-write-reply= with ~ement-room-send-org-filter~ set 
```

Which is precisely what I typed, but I expected to be formatted differently since it went through the filter. 

I have this set:

```emacs-lisp
(custom-set-variables
...
'(ement-room-send-message-filter 'ement-room-send-org-filter)
...
)
```

Unfortunately, this is all that prints in the `*Messages*` buffer, so can't see the entire message (it got ellipsized)...

```emacs-lisp
Result: (("format" . "org.matrix.custom.html") ("formatted_body" . "<p>\n&gt; &lt;wolfjb&gt; test message - debugging, ...") ("m.relates_to" ("m.in_reply_to" ("event_id" . "$wfw937rt0sQ688M73X4e3Vrt9pwpXUPSqkFPVDhMias"))) ("format" . "org.matrix.custom.html") ("formatted_body" . "<mx-reply>\n  <blockquote>\n    <a href=\"https://mat...") ("msgtype" . "m.text") ("body" . "> <wolfjb> test message - debugging, please ignore..."))
```

Hope this helps.  If I figure it out, I'll send a patch, but for the moment, I'm not sure where else to go.

**Comment by alphapapa** [comment]
@jeffbowman You can press `v` on an event to see the raw event from the server.  You'll be able to see the plain-text body and the formatted body.

You can set variables like `print-length` to prevent eliding strings.  There are several such variables, so use `M-x apropos-variable RET print- RET` to see them all.
