### ISSUE TITLE
Sending messages with Pantalaimon seems to time out

### ISSUE THREAD

**Issue by seanfarley** [alphapapa/ement.el#33]
Receiving messages seems to work (I can read encrypted messages, yay) but when I try to send a message nothing appears to POST. Is it possible you can test a pantalaimon instance on your own?

**Comment by alphapapa** [comment]
Other users are using it with Pantalaimon successfully.

**Comment by seanfarley** [comment]
Damn! Ok, thanks for the heads up; I'll investigate my end!

**Comment by seanfarley** [comment]
By the way, thanks for such awesome emacs packages!

**Comment by alphapapa** [comment]
Thanks for the kind words.  Please let me know what you find out.  I might try using Pantalaimon myself eventually, but not anytime soon.

**Comment by alphapapa** [comment]
@seanfarley  Note as well that this might be an issue with transient, Emacs process-related problems I've been occasionally seeing in `plz`.  I've been trying to solve them, but I ended up filing a report of a possible bug in Emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50166  In the meantime, `plz` seems 99.9% reliable in my using it with Ement.el.  

So if you do encounter any problems like this, please retry a few times, or even consider restarting Emacs, because it might be, somehow, an issue with Emacs's internal, process-related bookkeeping.  Also, please let me know, if it happens again, whether your Emacs process is also running a lot of other processes unrelated to Ement.el.  That might help understand whether this problem is related to that one.

**Comment by seanfarley** [comment]
Ok, will do! I'll do some more testing of it tomorrow

**Comment by seanfarley** [comment]
Actually, decided to debug it now ^_^ This is something weird with my setup. Everything works if I use `send-anyways` so I'll look into that. Thanks for the help and getting me on the right track!

**Comment by alphapapa** [comment]
What's `send-anyways`?  Googling didn't seem to find what you mean.

**Comment by seanfarley** [comment]
Sorry, it's a command to `panctl`. It turns out that I had an unverified session so pantaliamon was holding my messages back. Manually marking that random session (from a web client I was testing) as verified fixed everything. I imagine deleting that session would have worked, too.

Reading the help for `send-anyways` explains why it didn't send any messages (but it was completely unclear to me as a user):

https://github.com/matrix-org/pantalaimon/blob/master/docs/man/panctl.md

**Comment by alphapapa** [comment]
Ah, thanks.  Well, I guess we can close this then.  Please let me know if you have any other trouble.

**Comment by seanfarley** [comment]
No, thank you for your help! I think a big lesson to take away from this is to run `panctl` when there are errors because they will print some (maybe helpful) messages. Thanks again!
