### ISSUE TITLE
Password login fails

### ISSUE THREAD

**Issue by mekeor** [alphapapa/ement.el#4]
I installed plz and ement per straight, like this:

```elisp
(use-package plz
  :straight (plz :host github :repo "alphapapa/plz.el"))

(use-package ement
  :straight (ement :host github :repo "alphapapa/ement.el"))
```

When I run `M-x ement-connect`, I'm asked for login-credentials but it does not do anything then. Same in IELM:

```
ELISP> (ement-connect "NICK@:matrix.org" "PASSWORD")
#<process plz-request-curl>
```

I also tried to debug it (with `edebug`) but I could not understand much.

What's wrong? Any idea? :)

**Comment by alphapapa** [comment]
1.  Try typing in your username without an "@".
2.  Try waiting 30-60 seconds.
3. What is displayed in the messages buffer?

**Comment by mekeor** [comment]
Thanks for the quick response :) Here's what the messages-buffer says:

```
error in process sentinel: Ement API error: (#s(plz-error nil #s(plz-response 2 403 ((date . "Tue, 13 Jul 2021 13:53:23 GMT") (content-type . "application/json") (synapse-trace-id . "XXX") (cache-control . "no-cache, no-store, must-revalidate") (access-control-allow-origin . "*") (access-control-allow-methods . "GET, HEAD, POST, PUT, DELETE, OPTIONS") (access-control-allow-headers . "X-Requested-With, Content-Type, Authorization, Date") (permissions-policy . "interest-cohort=()") (cf-cache-status . "DYNAMIC") (expect-ct . "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"") (server . "cloudflare") (cf-ray . "XXX") (content-encoding . "gzip")) "{\"errcode\":\"M_FORBIDDEN\",\"error\":\"Invalid password\"}") nil))
```

Which is weird because I'm just tested the password again, and it works with the Element (former Riot) matrix-client.

**Comment by alphapapa** [comment]
You didn't mention the first suggestion I made.  Did you try that?

**Comment by okybr** [comment]
@alphapapa, yes, I did, and it helped! Because without the `@`, I do get an error message, at least :)

**Comment by okybr** [comment]
That error message, which I posted ;)

**Comment by alphapapa** [comment]
Thanks, I can confirm this bug.  I don't know when it started happening, because AFAIK it used to work.  I don't notice the problem in my normal use because my cached token still works.

I don't know how soon I'll be able to fix this.  In the meantime, you could try my other Matrix client, https://github.com/alphapapa/matrix-client.el  I guess logging in should still work with it, unless something changed on Matrix's end regarding it, too.  If it does work, the two clients currently share the same token file (which also needs to be fixed, but it's a WIP), so you could then exit matrix-client and connect with Ement.  Note that in matrix-client as well, you need to enable token-saving by customizing the appropriate option.

**Comment by alphapapa** [comment]
Oh, it was just a silly oversight, which I didn't notice by my not having used the password login code myself.  That should fix it.  Thanks for reporting.

**Comment by mekeor** [comment]
@alphapapa, it works! coool! thank you for fixing :)
