### ISSUE TITLE
Workaround for infinite-loop/out-of-memory when printing backtraces: `(setq print-circle t)`

### ISSUE THREAD

**Issue by piater** [alphapapa/ement.el#41]
I have a weird issue: Occasionally ement suddenly runs amok, locking up emacs. top shows emacs fully loading a CPU and rapidly eating memory. If I don't kill emacs at this stage, the OOM killer will do it for me after a few 10s of seconds. (I have 16G RAM and no swap.)

I have not been able to reproduce it deterministically. My impression is that there is a risk of this happening when I run an ement command such as ement-list-buffers while ement is busy doing something (sync'ing in the background?).

Perhaps this is already enough information to suggest where to look for a cause? Or perhaps someone has a suggestion of how to debug this?

Edit: IIRC when this happens the bell is active (I use visible-bell t), and there's an ement message in the minibuffer. I instrumented my emacs to log all messages to persistent storage. Perhaps this will reveal a clue when this issue happens next.

**Comment by alphapapa** [comment]
Hi,

Thanks for reporting.  I've occasionally seen this myself in the past, but not recently.  I haven't been able to narrow down a cause either, but I think it might be related to displaying Unicode characters, because sometimes I've been able to cause a similar behavior by using `C-u C-x =` with point on a Unicode character (like a reaction emoji).  I feel like it's actually a bug in Emacs that something in Ement.el happens to be exposing at times, but I can't be sure.

Please report all relevant software versions, like Emacs version, OS version, etc.  FWIW, I haven't seen this as often since I started running Ement.el on Emacs 28, so there might be some relevant improvements there.

**Comment by piater** [comment]
Intermediate heads-up: The issue has not reoccurred since my previous post. At some point we should probably just close this bug.

**Comment by alphapapa** [comment]
@piater Thanks for the update.  ISTR someone (maybe Ted?) mentioning it happening since you filed this, so I'm not sure it's fixed yet.  I'll leave it open for a while longer so anyone else who encounters it can report here.

**Comment by piater** [comment]
It happened to me again. I was entering a group. Its status line indicated that it was not syncing (despite auto sync); this happens quite often, and I routinely hit `g` to reconnect. But this time Emacs locked up and ate memory until I killed it. Unfortunately, the logged messages do not provide a clue. The last message was:

    Ement: Sync timed out (@...).  Syncing again...

So again, I suspect what triggered the bug was me hitting `g` while ement was already reconnecting. But I can't be sure. And again, the visible bell was active, but I don't recall whether it came on or was already on when I hit `g`.

**Comment by piater** [comment]
Had this(?) issue again. I was launching ssh from a shell buffer. While the minibuffer was waiting for my password, an ement message (too fast to read but looked like the usual sync-failure warning) hijacked the minibuffer for a split second. Afterwards, the password prompt reappeared in the minibuffer, but emacs was stuck, using 100% of a CPU core, and crashed a few tens of seconds later.

This seems to confirm that there is an issue with ement's unsolicited use of the minibuffer interfering with other uses of the minibuffer.

Writing this, I cannot think of any other emacs functionality using the minibuffer in this way (spewing messages at arbitrary moments without being triggered by user interaction). Perhaps the minibuffer is just not meant to be used in this way? In any case, I find this way of messaging quite disturbing as it interferes with other uses of the minibuffer, even when it does not crash emacs. A better way, IMO, would be to log messages in a dedicated ement-log buffer, which can optionally be configured to pop up on receipt of a new message. Or use desktop notifications.

**Comment by alphapapa** [comment]
@piater Thanks for the report.

I don't think the minibuffer is related to the problem.  Emacs is designed to work that way, so any background process can output a message to it at any time--that's why the error was displayed momentarily and then resumed the password prompt.

As best I can tell, from having seen this bug myself occasionally, it seems to be due to either a) certain events being received with certain data in them that Ement doesn't correctly handle; or b) certain Unicode characters that Emacs itself doesn't like (which would probably indicate a bug in Emacs, which is possible but unlikely).

As I said a few messages ago: Please report all relevant software versions, like Emacs version, OS version, GUI toolkit, etc.  Please include the version of `libcairo` you have installed as well.  FWIW, I haven't seen this as often since I started running Ement.el on Emacs 28, so there might be some relevant improvements there.

**Comment by piater** [comment]
I run Arch Linux and sway.

M-x emacs-version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-02-26

This is emacs-git from the AUR built using its unchanged PKGBUILD, i.e., vanilla upstream emacs (commit a2768c2f74) with JIT (native compilation), PGTK (pure GTK3 - native Wayland) and Xinput2 support enabled.

Let me know if I can provide more help of any sort.

**Comment by piater** [comment]
I can't easily downgrade my production environment because I've been moving forward my init.el and other things. 

In any case, the root problem is that we don't know whether and how this can be reproduced in _any_ version of emacs. So I fear the best I can realistically do is business as usual and report back when some new clues show up...

**Comment by alphapapa** [comment]
To all experiencing this problem, please try this: Check the value of the variable `print-circle`.  If it is nil, set it to t, then try to reproduce this problem (or if you don't know exactly how to, just use Ement normally again).  Changing the value of that variable may prevent the apparent infinite loop/OOM problem and allow a useful backtrace to be shown quickly.  (Ement uses circular data structures for some things, which might cause this problem when Emacs tries to print a backtrace.  It might be a good idea to permanently set `print-circle` to t in your Emacs config.)

**Comment by trev-dev** [comment]
Just to chime in I see this happen in emacsclient/daemon. Really not sure if that's related. I am running with `(print-circle t)` now

**Comment by alphapapa** [comment]
Do you mean that it happened before or after setting print-circle?

**Comment by trev-dev** [comment]
It happened about 3 times prior. I didn't catch on to what was happening until the 3rd time, where I opened up a system monitor and saw `emacs --daemon` was consuming 12-14Gb and sort of floating around there until I managed to pkill it.

**Comment by alphapapa** [comment]
Yes, it's unfortunate that this happens when printing a backtrace containing circular structures.  I wonder if there's a way to set `print-circle` just for Ement's backtraces.  Maybe I should ask on emacs-devel.

**Comment by alphapapa** [comment]
Hopefully that commit solves this problem for good (or until I accidentally make another circular data structure...).  I removed the suggestion in the readme to set `print-circle` in one's Emacs config, and I've unset it in mine.  Please let me know if this infinite-loop/OOM problem happens again.
