### ISSUE TITLE
ement.el for ElementOne

### ISSUE THREAD

**Issue by carlhenrikek** [alphapapa/ement.el#51]
Hi,

Even though this is probably an issue on Elements side. I've registered for ElementOne and sadly I can no longer use ement.el. It worked fine with the free matrix.org hosting. Is there anything that can be done on ement.el side or is there something that I can push to Elements side?

This is the output from running ement-connect

Ement: Checking server’s login flows...
error in process sentinel: Matrix server doesn’t support m.login.password login flow.  Supported flows: nil

**Comment by alphapapa** [comment]
Hi,

I think #24 is the relevant issue, but I haven't used ElementOne myself, so I'm not sure.  If #24 is the issue, please comment there with any information you may have.  If it's not the same problem, then some more investigation is needed about what kinds of login flows ElementOne requires.

Also, there may be a bug here, as there should be some supported flows listed in the error rather than nil.

Thanks.

**Comment by carlhenrikek** [comment]
Thank you, you are absolutely right. It is the same issue. Should I close this one?

**Comment by alphapapa** [comment]
Thanks.  I'll note that in #24's title.
