### ISSUE TITLE
Connection fails with pantalaimon

### ISSUE THREAD

**Issue by jonascant** [alphapapa/ement.el#54]
Hi, i always get the following error, trying to connect to matrix.org via pantalaimon:
`error in process sentinel: Ement API error: "Ement: Unrecognized network error", #s(plz-error nil #s(plz-response 1.1 401 ((access-control-allow-headers . "Origin, X-Requested-With, Content-Type, Accept, Authorization") (access-control-allow-methods . "GET, POST, PUT, DELETE, OPTIONS") (access-control-allow-origin . "*") (content-type . "application/json") (content-length . "84") (date . "Mon, 21 Feb 2022 16:51:38 GMT") (server . "Python/3.9 aiohttp/3.8.1")) "{\"errcode\":\"M_UNKNOWN_TOKEN\",\"error\":\"Invalid macaroon passed.\",\"soft_logout\":false}") nil) [2 times]
`

**Comment by alphapapa** [comment]
Hi,

I don't use Pantalaimon myself, so I can't offer any help.  I'd suggest asking in the `#ement.el:matrix.org` room, as there are several users there who could probably help.

**Comment by seanfarley** [comment]
Can you please just join one encrypted room to test this? It's frustrating that you just straight up mark these issues as "won't fix" aka "can't be bothered to join a single room with encyrption"

**Comment by alphapapa** [comment]
@seanfarley I'll try to respond to you as politely as possible.  Here are a few points in no particular order:

* I don't use Pantalaimon.  I may or may not ever use it (I have little interest in using Matrix for encrypted chat).  
* I know nothing about configuring or using it.  In order to offer any help, I'd have to download it, install it, read its documentation, configure it, attempt to use it, etc., just like any other software I don't already use.
* I've already spent some time adding necessary support to this client so that Pantalaimon can be used with it.
* Several users are in the chat room who do use it successfully.  They have experience troubleshooting it and configuring it, and I've seen them help others with it before.
* You may have noticed that I haven't had much time to work on my GitHub projects for a while.  I still don't.  Since the beginning of the year, both of my parents have been in and out of the hospital, and still are right now.  I'm also trying to find a new job, deal with various other IRL issues, etc.

Given all of that, I can't justify spending several hours trying to discern whether there is a new bug here, or whether it's just a user configuration problem.  Given that people are using Pantalaimon successfully, I'm guessing that it's the latter, in which case you should be able to get help from other users in the chat room.

If someone can confirm that a bug exists, then I'll be glad to track it here.  Depending on the details, I couldn't promise to fix it myself, especially in any certain timeframe, unless someone wanted to sponsor my work; like any FOSS software, it's done in my spare time, which I don't have much of now.

I hope you'll understand where I'm coming from.

**Comment by seanfarley** [comment]
Perhaps it's really just a frustration with the infinite feature matrix (no pun intended) with using the matrix protocol. I actually don't really like the encryption either but matrix insists on having that be the default for new rooms with the added frustration that you can't turn encryption off once it's enabled. So I'm left with an emacs chat client (which is cool and familiar since I'm coming from ERC and circe) that's leaves me opening up another app, grumble.

I am empathetic to personal issues and not having time, and I don't mean to criticize that part. I don't think my comment reflected that so I apologize. And yes, you're right about FOSS, so I'll pull back.

**Comment by alphapapa** [comment]
I share some of your frustration with the Matrix spec.  I hope that it doesn't get unmanageable in the future.

Maybe some of this problem would be alleviated when invitations are implemented in Ement.  That should allow starting new, non-encrypted chats.  Although the problem would remain of users who invite you to encrypted rooms.

Thanks for the kind words.  As a user, I understand the frustration of dealing with issues that remain unsolved for a long time.

Given the specific error shown, and given what little I know about Pantalaimon, it sounds like a problem with Pantalaimon rather than this client, which is why I closed this.  Again, if you or anyone else can troubleshoot this further and confirm that a bug exists, I'll be glad to do what I can to help fix it.

**Comment by seanfarley** [comment]
No problem or worries at all; I finally forked this so I could try my hand at getting to the root of it. You take care of yourself and those you care about first and foremost. I'll try to ease off the gas pedal :-)

**Comment by alphapapa** [comment]
Thank you.  Let me know if I can help you understand anything in the code or the spec.  You may also find these links helpful:

* https://github.com/alphapapa/ement.el/blob/meta/notes/NOTES.org
* https://github.com/alphapapa/ement.el/tree/meta/spec

**Comment by seanfarley** [comment]
I did but I forgot exactly what made it work. I *think* I had to use the pantalamion ctl program and manually "send anyway" for encrypted rooms.

**Comment by seanfarley** [comment]
> @seanfarley Facing the same trouble since I am using the signal bridge, did you manage to solve this problem and how ? Thanks !

I just did the whole process again and by using `panctl` a few times to verify the sessions (also had to make sure `VerifySessions = false`, the default, after I verified the session). It's a bit of whack-a-mole with pantalamoin but it's working well for me over the last day.

A few notes:
- using the signal bridge doesn't need pantalaimon at all (in fact, if you don't need pantalaimon, then don't use it)
- if you still have problems then you probably need to get some custom help configuring your client since I suspect it's a config issue
- I should probably blow away my pantalaimon session and start over so I can document the exact steps to make it work with encrypted rooms (on a mac at least)

Sorry to reply to such an old thread!
