### ISSUE TITLE
defalias in elemt-macros.el

### ISSUE THREAD

**Issue by phil-s** [alphapapa/ement.el#76]
This looks like a bug, except that some of the libraries have a top-level `(require 'elemt-macros)` which masks it?

`elemt-lib.el` does use the `(eval-when-compile ...)` wrapper you'd anticipate with a macro library, but `ement-api.el` and `ement-room.el` require it directly (and `ement.el` requires `ement-room.el`).

I imagine it would be better to move the `(defalias 'ement-progress-update #'ignore)` into `ement.el`, and then not have any byte-compiled code loading macros?

**Comment by alphapapa** [comment]
I don't understand.  What is the problem you're reporting?

**Comment by phil-s** [comment]
No problem manifesting right now; but libraries dedicated to macros are normally so that byte-compiled libraries don't need to require them at all; yet if you were to make *that* change then `ement-progress-update` wouldn't be defined when other code attempted to call that function.  So it seems wrong seeing a non-macro in that `ement-macros.el` library.  If it were moved, then I believe you could use `(eval-when-compile (require 'elemt-macros))` in general.

**Comment by alphapapa** [comment]
Ah, yes, well, my intention for having `ement-macros.el` isn't necessarily so that byte-compiled libraries can use `eval-when-compile` instead of requiring them at the top level.  IOW, I'm not adhering to that ideal strictly (IME hardly any other packages do so, anyway).  A few extra `require` calls at the top level, called once at load time, isn't a performance issue.  As well, keeping the alias definition with the associated macro definition is better for the programmer.

**Comment by phil-s** [comment]
FWIW I'd think that the "keeping the alias definition with the associated macro definition" issue could be solved with comments, and then there'd (probably) be nothing blocking the (admittedly minor) efficiency gain; but I'll close this now in any case.

**Comment by alphapapa** [comment]
You're right, but as much as I do try to write useful comments, I also know
how easily I overlook them when I'm trying to solve something quickly. So I
don't think it would be worth making this change now, but I do appreciate
your careful review of the code. Please let me know if you find other
improvements that could be made.
