### ISSUE TITLE
Void-function ement-list-rooms

### ISSUE THREAD

**Issue by geoffmacintosh** [alphapapa/ement.el#8]
I have an issue that seems like it should be my fault entirely, but I might be wrong because I don't understand what's going on exactly.

System:
```
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.4.0, NS appkit-2022.44 Version 11.3.1 (Build 20E241)) of 2021-06-03

MacOS 11.5 Big Sur on a 2013 MacBook

Plz.el (current head): 8d2654bba7bfa11525aef50f969c489c20ac0a43
Ement.el (current head): cd59430081a5eb8938e676585898bd48ddc9fa0b
```

I'm testing in `emacs -Q` with the following config (just pasted into scratch and eval):

```
(setq debug-on-error t)
(add-to-list 'load-path "~/.config/emacs/site-lisp/plz.el")
(add-to-list 'load-path "~/.config/emacs/site-lisp/ement.el")
(require 'ement)
(ement-connect "@geoff:custom.domain" "password")
```

Messages buffer: 
```
Ement: Checking server’s login flows...
"Ement: Checking server’s login flows..."
Ement: Logging in with password...
Ement: Sync request sent, waiting for response...
Ement: Response arrived after 0.34 seconds.  Reading 38.3k JSON response...
Ement: Reading JSON took 0.00 seconds
Ement: Reading events... 
Ement: Sync request sent, waiting for response...
Entering debugger...
```

Then repeating every few seconds:
```
Ement: Response arrived after 30.37 seconds.  Reading 944 JSON response...
Ement: Reading JSON took 0.00 seconds
Ement: Reading events... 
Ement: Sync request sent, waiting for response...
run-hook-with-args: Symbol’s function definition is void: ement-list-rooms
```

The debugger begins with
```
Debugger entered--Lisp error: (void-function ement-list-rooms)
```

And then a lot of other stuff. It doesn't seem to mention my password, but does have a lot of tokens, ids and such that might give away my login information. I'd be happy to provide additional details or just send the entire Backtrace log (privately).

**Comment by alphapapa** [comment]
Hi Geoff,

Yes, this is because you aren't installing it as a package but just loading the files.  The key is here:

https://github.com/alphapapa/ement.el/blob/cd59430081a5eb8938e676585898bd48ddc9fa0b/ement-room-list.el#L100

Since you aren't installing it as a package, the autoloads aren't generated, so Emacs doesn't know about that function alias.  That's why I wrote that note in the readme about installing it manually.  ;)

So there are 3 options:

1.  Install it as a package.
2. Generate the autoloads yourself.
3.  Manually load `ement-room-list` before calling `ement-connect`.

Note as well that, by not installing it as a package, the files aren't byte-compiled, so performance will be reduced (maybe not noticably, depending on the rooms you're in, and that's assuming that you aren't byte-compiling them yourself).

Issues like this are why I recommend installing it as a package.  I lint everything before pushing to catch problems like this, but that assumes that users are installing it rather than just loading it.

The good news is that, from looking at the messages, everything else appears to be working.  :)

**Comment by geoffmacintosh** [comment]
Well, it turns out I know so much less about Emacs' package system than I thought! Thanks so much for explaining what I've done wrong and offering ways to fix it. I really appreciate it, and I'll hopefully be able to return the favour by helping with something... when I learn a little bit more, it would seem. Thanks!

**Comment by alphapapa** [comment]
Sure.  Please let me know if you encounter any bugs or have any suggestions.
